### ISSUE TITLE
Overcome Youtube throttling of youtube-dl, conserve bandwidth

### ISSUE THREAD

**Issue by emulti** [ninebysix/MooTube#1]
Thank you very much for creating this program!
Testing it out on laptop and Pinephone, I was puzzled to find that it was constantly buffering video playback.
Hacking player.py to reduce video quality to 360p and force webm (about half mp4 file size) encoding was one workaround, but eventually I found the issue was caused by Google throttling downloads via youtube-dl to 50-70 kB/sec.

There is a fork of youtube-dl called yt-dlp that uses an Android API to overcome the deliberate throttling issue. 
Versions of mpv  later than 0.34 use yt-dlp automatically over youtube-dl if it is found to be installed. This allows a return to 720p video and fast download speeds.

However, I found that I can see no perceptible difference between 720p and 480p formats on the Pinephone screen.   It would probably be worth restricting playback to 480p (or offering a config option) to conserve both bandwidth and mobile data. The webm format is also preferable if available, as file size is about half of the mp4 version, for minimal difference in video quality. 
For the moment I am using 
`ytdl_format='(webm[height<=480]+bestaudio/bestvideo[height<=480]+bestaudio)'` 
and will test further.

**Comment by jakeday** [comment]
Thank you for pointing this out! I updated the app with these suggestions.
